require:
  - ../lib/runger_style/cops/require_all_custom_cops.rb

AllCops:
  EnabledByDefault: true
  ParserEngine: parser_prism
  TargetRubyVersion: 3.4
  UseCache: true
Bundler/GemComment:
  Enabled: false
Bundler/GemVersion:
  Enabled: false
Layout:
  Exclude:
    - db/schema.rb
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/ClassStructure:
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_class_methods
    - initializer
    - public_methods
    - protected_methods
    - private_methods
Layout/ConditionPosition:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterMultilineCondition:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/FirstArgumentIndentation:
  Enabled: false # Instead, we use RungerStyle/FirstArgumentIndentation.
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstMethodArgumentLineBreak:
  AllowMultilineFinalElement: true
Layout/LineEndStringConcatenationIndentation:
  Exclude:
    - bin/*
Layout/LineLength:
  AllowedPatterns:
    # Ignore line length if the line is a comment without any spaces; it's probably not something we
    # can fix (e.g. a long file path):
    - !ruby/regexp /^ *#? [\S]+$/
    # Ignore long annotate comments about indexes.
    - !ruby/regexp /^#\s+idx_on_/
    # Ignore RSpec description strings:
    - !ruby/regexp /^ *(context|describe|it) ['"].*['"].* do$/
  Max: 100
Layout/MultilineAssignmentLayout:
  SupportedTypes:
    - block
    - case
    - class
    - if
    - kwbegin
    - module
    - send # This (method calls) is not in the default list.
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/RedundantLineBreak:
  Enabled: false
Layout/SingleLineBlockChain:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*.rb
Lint/ConstantResolution:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
Naming/RescuedExceptionsVariableName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
RungerStyle/FirstArgumentIndentation:
  EnforcedStyle: consistent_relative_to_receiver
  MemoizingMethods:
    - memo_wise
    - memoize
  SupportedStyles:
    - consistent_relative_to_receiver
Style:
  Exclude:
    - db/schema.rb
Style/ArgumentsForwarding:
  Enabled: false
Style/ArrayFirstLast:
  Enabled: false
Style/BlockDelimiters:
  Enabled: true
  AllowedMethods:
    - expect
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/ClassMethodsDefinitions:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false
Style/ConstantVisibility:
  Enabled: false
Style/Copyright:
  Enabled: false
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GlobalStdStream:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always
Style/IfUnlessModifier:
  Enabled: false
Style/ImplicitRuntimeError:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/IpAddresses:
  AllowedAddresses:
    - "::"
    - "::1"
    - "127.0.0.1"
Style/Lambda:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - add_column
    - add_foreign_key
    - add_index
    - add_reference
    - and
    - belongs_to
    - bigint
    - boolean
    - change
    - change_column
    - change_column_default
    - change_column_null
    - change_table
    - create_table
    - datetime
    - desc
    - describe
    - drop_table
    - fail
    - file
    - float
    - foreign_key
    - gem
    - head
    - include
    - index
    - inet
    - integer
    - json
    - jsonb
    - load
    - not_to
    - p
    - print
    - puts
    - references
    - remove_column
    - remove_index
    - render
    - require
    - require_relative
    - ruby
    - run
    - source
    - string
    - text
    - timestamp
    - timestamps
    - to
    - visit
Style/MethodCalledOnDoEndBlock:
  Enabled: false
Style/MissingElse:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineMethodSignature:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/RedundantArgument:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RequireOrder:
  Exclude:
    - bin/*
    - spec/spec_helper.rb
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
  Enabled: true
Style/Send:
  Exclude:
    - spec/**/*.rb
Style/SignalException:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TopLevelMethodDefinition:
  Exclude:
    - db/datamigrate/**/*.rb
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
