inherit_from:
  - rulesets/capybara.yml
  - rulesets/default.yml
  - rulesets/factory_bot.yml
  - rulesets/performance.yml
  - rulesets/rails.yml
  - rulesets/rake.yml
  - rulesets/rspec_rails.yml
  - rulesets/rspec.yml

# Load the Rails cops to check that they work, but disable them because this isn't a Rails project.
Rails:
  Enabled: false
