name: Run RuboCop and RSpec

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Set up
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bin/rubocop --format clang --color 2> >(tee /tmp/rubocop_stderr >&2)
    - name: Check that RuboCop didn't write anything to stderr
      run: |
        if [[ -s /tmp/rubocop_stderr ]] ; then
          echo "Error: stderr was not empty" >&2
          exit 1
        fi
    - name: Run RSpec tests
      run: bin/rspec --format progress
    - name: Ensure alpha version
      run: grep alpha $(find . -type f -name version.rb)
    - name: Ensure no git diff
      run: git diff --exit-code && git diff-index --quiet --cached HEAD
    - name: Ensure "## Unreleased" is in CHANGELOG.md
      run: grep "^## Unreleased" CHANGELOG.md
