name: Run Rubocop

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - name: Set up
      run: |
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3
    - name: Run Rubocop
      run: bin/rubocop
